// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzwcpeynargzwadgnvid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6d2NwZXluYXJnendhZGdudmlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5OTg2NTEsImV4cCI6MjA3MzU3NDY1MX0.T0U9vMSczCHYTqm2o1J2_BKA2dVuVp6M0UK3Wa4ZfWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});